# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]  # Update with your Alertmanager address.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # Uncomment and add your custom rule files here.
  # - "alerts.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # Prometheus self-scrape job
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Jenkins monitoring job
  - job_name: "jenkins"
    metrics_path: /prometheus
    static_configs:
      - targets: ["192.168.192.1:8080"]  # Update port if needed.
